# Agradecimentos {.unnumbered}

Obrigado aos nossos revisores por seu apoio crítico a este projeto.[^agradecimentos-1]

[^agradecimentos-1]: Este agradecimentos, assim como as seções a seguir, são traduções do texto base do *Planetary Health Education Framework*.

Um caloroso agradecimento aos outros integrantes da Aliança para Saúde Planetária \[*Planetary Health Alliance*\] que contribuíram para o desenvolvimento desta antologia, especificamente Sam Myers, Marie Studer, Jeremy Pivor, Max Zimberg, Joanna Wagner, e um agradecimento especial a Arielle Blacklow por seus esforços na edição de texto.

Obrigado à revista *Lancet Planetary Health* por publicar nosso trabalho.

À rede da *Planetary Health Alliance*, um profundo agradecimento por contribuindo com inúmeras ideias e comentários ao longo deste projeto, especialmente ao Dr. John Latta, Dra. Katharina Wabnitz, Dra. Tatiana de Camargo e Lewin Han por seus extensos comentários nos rascunhos iniciais deste plano.

Os editores gostariam de agradecer pessoalmente a todos os autores por seu apoio e sabedoria ao longo deste projeto de 18 meses.
