# Anexo {#sec-anexo .unnumbered}

## **Agrupamento de competências que serviram para orientar a criação do Plano de Educação em Saúde Planetária**[^anexo-1]

[^anexo-1]: Durante o processo de tradução, percebeu-se que houve uma duplicação da competência 22, reproduzida na competência 43, no texto base (versão em inglês). Aqui, essa duplicação foi retirada e, portanto, a numeração encontra-se diferente da do texto base.

1\. Identificar como mudanças antrópicas nos sistemas naturais influenciam desfechos de saúde;

2\. Compreender o impacto desproporcional das mudanças climáticas e ambientais nos povos indígenas, e a força dos modos de saber e fazer indígenas para ajudar a construir uma relação equitativa entre as pessoas e o meio ambiente;

3\. Incorporar sistemas de conhecimento tradicionais, incluindo visões de mundo indígenas, nas ações de Saúde Planetária;

4\. Implementar estratégias para engajar populações marginalizadas e vulneráveis ​​nas tomadas de decisões que afetam a saúde e o bem-estar das populações e dos ecossistemas;

5\. Usar processos éticos, empoderadores, culturalmente apropriados e participativos para implementar ações de Saúde Planetária;

6\. Descrever como o contexto cultural influencia as percepções de saúde e doença, bem como a percepção das relações das pessoas com seu ambiente natural e construído;

7\. Examinar as interações entre as escalas geográficas (local/regional/global -- micro/meso/macro), escalas temporais (passado/presente/futuro -- prioridade máxima/prioridade baixa -- urgente/eletivo), fatores socioeconômicos e os contextos político e cultural que moldam o cenário de Saúde Planetária;

8\. Aplicar princípios e enquadramentos éticos às questões, desafios e práticas profissionais relacionadas à Saúde Planetária, relacionadas, mas não restritas a: definição de prioridades, distribuição de recursos, ao princípio da precaução, uso de tecnologia apropriada, conhecimento cultural e tradicional, moralidades subjetivas e dinâmicas de poder;

9\. Desenvolver e comunicar metas e objetivos apropriados, realistas e mensuráveis ​​para a Saúde Planetária;

10\. Compreender ligações cruciais, relações causa-efeito, relações não lineares, pontos de alavancagem, incerteza e ciclos de retroalimentação entre mudanças socioecológicas e saúde humana;

11\. Integrar conceitos de equidade, justiça transgeracional, marginalização, ciclo da pobreza, estruturas de poder, limites planetários, vulnerabilidade, resiliência nas análises e ações de Saúde Planetária;

12\. Apoiar o empoderamento, a participação, parceria e equidade para criar ambientes que promovam a saúde das comunidades e do planeta;

13\. Aplicar os princípios de justiça social e de direitos humanos na abordagem dos problemas de Saúde Planetária;

14\. Examinar como os contextos históricos, antropológicos, econômicos e políticos de nossa(s) sociedade(s) determinam nossos dilemas de Saúde Planetária hoje;

15\. Demonstrar a capacidade de trabalhar colaborativamente entre disciplinas, reconhecendo a variedade de perspectivas, habilidades e abordagens, e como elas se complementam em processos colaborativos e desfechos;

16\. Advogar junto a e em nome de indivíduos, comunidades e organizações para melhorar a saúde e bem-estar de humanos e do ambiente;

17\. Coletar, avaliar e reunir/sintetizar/integrar dados qualitativos e quantitativos, informações e literatura relevantes para informar ações de Saúde Planetária;

18\. Compartilhar conhecimento, habilidades e recursos para melhorar os programas, a infraestrutura e força de trabalho de Saúde Planetária, com foco no fortalecimento de capacidades;

19\. Comunicar de forma eficaz, usando técnicas e tecnologias apropriadas, tanto oralmente quanto por escrito, descobertas científicas para a comunidade científica, especialistas não relacionados à Saúde Planetária, o público leigo, a mídia e formuladores de políticas;

20\. Apreciar e reconhecer as fontes de incerteza e ser capaz ou ter capacidade de prever as consequências inesperadas da mudança ambiental, tanto positivas quanto negativas;

21\. Compreender as perspectivas e marcos históricos que formaram as bases para o campo da Saúde Planetária, incluindo perspectivas que foram marginalizadas ou ignoradas;

22\. Usar métodos apropriados de avaliação e pesquisa, em parceria com as partes interessadas, para determinar o alcance, o impacto e a eficácia de ações de Saúde Planetária;

23\. Advogar em prol de programas políticos, sociais ou econômicos, locais e globais, que integrem o bem-estar de populações e sistemas naturais;

24\. Facilitar abordagens que permitam que comunidades e grupos articulem suas necessidades e defendam recursos e capacidades necessários para ações de Saúde Planetária;

25\. Apreciar o papel que a organização na comunidade, as abordagens desenvolvidas pelas bases \[*bottom-up approaches*\] e a construção de movimento têm no processo político local e global;

26\. Identificar as fontes apropriadas de informação para responder às questões de saúde da população e do ecossistema;

27\. Exibir valores e habilidades interprofissionais que demonstrem respeito por, e consciência de, culturas, valores, papéis/responsabilidades e especialidades únicas, representados por outros profissionais e grupos que trabalham com Saúde Planetária;

28\. Descrever sua própria compreensão e senso de conexão com a natureza;

29\. Compreender as perspectivas de várias partes interessadas locais e globais;

30\. Identificar métodos para garantir a sustentabilidade do programa;

31\. Aplicar técnicas de monitoramento e avaliação de programas e políticas de Saúde Planetária;

32\. Traduzir resultados de pesquisas e outras formas de conhecimento em políticas, programas comunitários, intervenções e educação pública de forma sustentável, culturalmente relevante e economicamente viável;

33\. Planejar, implementar e avaliar um programa baseado em evidências para abordar um desafio em Saúde Planetária;

34\. Propor estratégias que alcancem "co-benefícios para a saúde";

35\. Demonstrar valores individuais e escolhas de vida que promovam bem-estar e que, simultaneamente, promovem um ambiente/ecossistema local e global saudável;

36\. Adotar o princípio da transdisciplinaridade;

37\. Demonstrar autorreflexão crítica e humildade cultural e intelectual;

38\. Aplicar a consciência de valores culturais, sistemas e práticas políticas ao delineamento ou implementação de políticas, ou programas;

39\. Identificar partes interessadas e construir coalizões e parcerias para influenciar políticas para abordar desafios da Saúde Planetária;

40\. Desenvolver um senso de responsabilidade para consigo mesmo, para com a comunidade, sociedade e o ambiente natural;

41\. Demonstrar empatia, compaixão, integridade, consideração e respeito pelos outros em todos os aspectos da prática profissional;

42\. Integrar bens e recursos comunitários para melhorar a saúde dos seres humanos e do meio ambiente/planeta;

43\. Incluir representantes de diversos públicos e disciplinas em parcerias e promover o aprendizado interativo com esses parceiros;

44\. Usar habilidades de comunicação interpessoal para facilitar que indivíduos, grupos, comunidades e organizações melhorarem a saúde de populações e ecossistemas;

45\. Discutir as múltiplas dimensões do processo de formulação de políticas, incluindo os papéis da ética e da política informada por evidências;

46\. Ser capaz de trabalhar, planejar, delinear e implementar intervenções em condições de incerteza;

47\. Compreender o papel e as limitações das avaliações de impacto e das ferramentas de modelagem atuais;

48\. Desenvolver e implementar estratégias de comunicação apropriadas para divulgação eficaz, que utilizem ferramentas de comunicação persuasiva;

49\. Reconhecer limitações de habilidades, conhecimentos e capacidades;

50\. Aplicar estruturas de análise para entender a relação entre várias partes interessadas locais e globais e como as mesmas influenciam desfechos de Saúde Planetária;

51\. Influenciar a opinião política e pública sobre questões de Saúde Planetária;

52\. Reconhecer seus próprios fundamentos epistemológicos para interagir efetivamente entre sistemas de conhecimento;

53\. Avaliar necessidades e recursos disponíveis em parceria com partes interessadas;

54\. Desenvolver apreciação pela importância da escuta ativa como parte de uma comunicação eficaz;

55\. Demonstrar capacidade de adaptar o conhecimento, as habilidades e a prática de disciplinas-específicas em um ambiente com recursos limitados;

56\. Compreender o conceito e abordagem da Análise do Ciclo de Vida.
