# Definições Fundamentais {.unnumbered}

## **Agenciamento** {.unnumbered}

"Capacidade de um indivíduo escolher ativa e independentemente, e gerar mudança; livre arbítrio ou auto-determinação" [@open_education_sociology_dictionary_agency_2021].

## **Antropoceno** {.unnumbered}

Um conceito que marca o início de uma época geológica proposta, em que a força dominante que molda as condições biofísicas da Terra é a atividade humana. O termo combina os radicais gregos "antropo-", que significa "humano", com *kainos* ou "-cene", o sufixo padrão para "época" no tempo geológico. Paul J. Crutzen e Eugene Stoermer, laureados pelo prêmio Nobel, cunharam o termo em um ensaio numa revista científica de sistemas terrestres [@steffen_trajectory_2015].

## **A Grande Aceleração** {.unnumbered}

Uma mudança global após a Segunda Guerra Mundial, manifesta em um aumento massivo da taxa de crescimento das atividades humanas e mudanças demográficas iniciadas por volta de 1950. Conforme o Programa Internacional Geosfera-Biosfera \[IGBP\], "a segunda metade do século XX é única na história da existência humana. Muitas atividades humanas alcançaram pontos altos em algum tempo do Século XX e aceleraram bruscamente no final do século. Os últimos 60 anos mostraram, sem dúvida, as mais profundas transformações das relações humanas com o mundo natural na história da humanidade" [@international_geosphere-biosphere_programme_great_2015].

## **A Grande Transição** {.unnumbered}

Uma mudança fundamental em como as pessoas e os sistemas humanas -- políticos, econômicos e sociais -- interagem para formar os mais altos padrões alcançáveis de saúde da humanidade e do estado dos sistemas Naturais da Terra. É uma transformação de valores, do individualismo, consumismo e dominação da Natureza para solidariedade, qualidade de vida e resiliência ecológica. Pode ser mensurada e então alcançada via a melhoria da saúde e do ambiente, ampliação da solidariedade humana e qualidade de todas as vidas [@raskin_great_2002].

## **Conhecimentos Tradicionais Indígenas** {.unnumbered}

"Refere-se aos conhecimentos, às inovações e práticas de pessoas indígenas. Desenvolvidos a partir de experiências adquiridas ao longo de séculos e adaptas para a cultura e o ambiente local, os conhecimentos tradicionais são geralmente transmitidos oralmente de geração em geração. Tende a ser apropriado coletivamente e pode ser expresso em histórias, músicas, folclore, provérbios, valores culturais, crenças, rituais etc. É também referência para o uso tradicional e administração de terras, territórios e recursos, com práticas agricultoras indígenas que cuidam da Terra, sem esgotar seus recursos. Pessoas indígenas seguem tradições orais, com danças, pinturas, esculturas e outras expressões artísticas, praticadas e transmitidas por milênios" [@united_nations_permanent_2019].

## **Determinantes de saúde** {.unnumbered}

Conforme a Organização Mundial de Saúde [@world_health_organization_determinants_2017], os Determinantes da Saúde incluem: "o ambiente social e econômico, o ambiente físico, as características e comportamentos individuais da pessoa".

O contexto de vida das pessoas determina sua saúde, então culpar os indivíduos por terem uma saúde deficiente ou creditá-los por uma boa saúde é inapropriado. É improvável que indivíduos consigam controlar diretamente muitos dos determinantes de saúde. Estes determinantes -- ou coisas que tornam as pessoas saudáveis ou não -- estão entre fatores abaixo indicados, dentre muitos outros:

-   **Renda e estado social** -- renda mais elevada e estado social estão associados a melhor saúde. Quanto maior for o fosso entre as pessoas mais ricas e mais pobres, maiores serão as diferenças na saúde;

-   **Educação** -- baixos níveis de educação estão ligados a saúde precária, mais estresse e menor autoconfiança;

-   **Ambiente físico** -- água potável e ar limpo, locais de trabalho saudáveis, casas seguras, comunidades e estradas contribuem para uma boa saúde;

-   **Emprego e condições de trabalho** -- pessoas com emprego são mais saudáveis, particularmente as que têm mais controle sobre as suas condições de trabalho;

-   **Redes de apoio social** -- um maior apoio das famílias, amigos e comunidades está associado a uma melhor saúde;

-   **Cultura** -- costumes e tradições, crenças da família e da comunidade afetam a saúde;

-   **Genética** -- a hereditariedade desempenha um papel na determinação da longevidade, da saúde e da probabilidade de desenvolver certas doenças;

-   **Comportamento pessoal e capacidade de adaptação --** alimentação equilibrada, manter-se ativo, fumar, beber e como lidamos com o estresse e os desafios da vida, tudo afeta a saúde;

-   **Serviços de saúde** -- a acessibilidade e a utilização de serviços que previnem e tratam doenças influenciam a saúde;

-   **Gênero** -- homens e mulheres sofrem de diferentes tipos de doenças em diferentes idades.

## **Determinantes de saúde em animais** {.unnumbered}

Os determinantes de saúde aplicados aos animais podem incluir a biologia individual e populacional; o ambiente social do animal; a quantidade e qualidade do habitat para satisfazer as necessidades básicas do animal; o ambiente abiótico; fontes de mortalidade direta; e a mudança de expectativas humanas. Os determinantes utilizados na saúde humana e pública são diferentes para os animais, plantas e ecossistemas. Esta distinção é relevante se aplicada ao planejamento, desenvolvimento de políticas, e orientação de pesquisas. Modelos para outras espécies podem ajudar gestores a identificar prioridades de proteção da saúde e a promover ações para a vida selvagem e os seus habitats.

## **Diversidade epistemológica** {.unnumbered}

"Diversidade epistemológica é a capacidade ou possibilidade de produzir aparatos epistêmicos diversos e ricos para dar sentido ao mundo à nossa volta" [@gobbo_epistemic_2020]. Dados os diversos paradigmas de conhecimento decorrentes de culturas de todo o mundo, é essencial que estudiosos e educadores estejam familiarizados e considerem a integração de diferentes epistemologias. De fato, a diversidade epistemológica pode lançar luz sobre melhores caminhos em direção à Saúde Planetária.

## **Ecologia centrada em entes** {.unnumbered}

"Pessoas indígenas veem si mesmas e a Natureza como parte de uma extensa família ecológica que compartilha suas origens e ancestralidades. É uma percepção de que a vida em qualquer ambiente é viável somente quando humanos veem a vida ao seu redor como entes. Os entes, ou relativos, incluem todos os elementos naturais de um ecossistema. Pessoas indígenas são afetadas e afetam a vida ao seu redor. As interações resultantes da"ecologia centrada em entes" realçam e preservam o ecossistema. Interações são as trocas do ecossistema em funcionamento. Sem o reconhecimento humano de seu papel nas complexidades da vida num lugar, a vida sofre e perde sua sustentabilidade" [@salmon_kincentric_2000].

## **Equidade** {.unnumbered}

Equidade envolve a capacidade de justiça por meio do acesso aos mesmos recursos e oportunidades. Dadas as atuais disparidades sociais no capital financeiro, na educação, saúde, alimentação, habitação etc, a equidade pode envolver a distribuição desproporcionada de recursos a uma determinada população, com a finalidade de os elevar ao mesmo campo de condições que outros.

## **Inclusão/diversidade** {.unnumbered}

Inclusão e diversidade andam juntas, uma vez que devemos aceitar as diferenças um dos outros. Geralmente, diversidade refere-se às diferenças de raça, etnicidade, gênero, orientação sexual, religião, idade, origem nacional, estado socioeconômico, linguagem, perspectivas, epistemologias, valores e muito mais. Inclusão reúne "indivíduos e/ou grupos tradicionalmente excluídos de processos, atividades e decisões políticas de maneira que o poder seja partilhado" [@icma_glossary_2021].

## **Interconexão** {.unnumbered}

Descreve um estado não dual de ser/estar, que existe na Natureza. Para humanos, a experiência de interconexão na Natureza tem sido descrita como "um estado estável de consciência composto por traços experienciais simbióticos, cognitivos e afetivos, que refletem, através de atitudes e comportamentos consistentes, uma percepção de inter-relação entre si mesmo e o resto da natureza" [@zylstra_connectedness_2014].

## **Justiça Social, Ambiental, Distributiva, Intergeracional e Multiespécie** {.unnumbered}

Mais fundamentalmente, a justiça é o conceito de imparcialidade. A justiça social, ambiental, distributiva, intergeracional e multiespécie estende o conceito de justiça às estruturas sociais, sistemas ambientais, espécies e ecossistemas por meio da consideração de distribuições geográficas e temporais.

## **Limites planetários** {.unnumbered}

Conforme o Centro de Resiliência de Estocolmo [@stockholm_resilience_centre_nine_2009], "o conceito de limites planetários apresenta um conjunto de nove limites planetários dentro dos quais a humanidade pode continuar a se desenvolver e prosperar por gerações a devir." Esses nove limites incluem: depleção do ozônio estratosférico, perda da integridade da biosfera (perda da biodiversidade e extinções), mudanças climáticas, acidificação dos oceanos, consumo de água potável e ciclo hidrológico global, mudanças nos sistemas terrestres, fluxos de nitrogênio e fósforo na biosfera e oceanos, e carga atmosférica de aerossóis.

## **Mudança ambiental global** {.unnumbered}

Disrupções e mudanças aceleradas, pervasivas nos sistemas naturais da Terra, incluindo alterações climáticas, perda de biodiversidade, alterações na utilização e cobertura do solo, escassez de recursos, poluição global, e ciclos biogeoquímicos alterados. Estas alterações das condições biofísicas da Terra são diferentes dos tipos de alterações ambientais classicamente abordados pelo campo da saúde ambiental, que foca na introdução de metais pesados, desreguladores endócrinos, bifenilpoliclorado (PCB), e outras toxinas introduzidas em nosso ambiente por humanos.

## **Natureza** {.unnumbered}

Frequentemente entendida como o sistema biofísico não humano, que inclui a flora, fauna e as formações geológicas que ocorrem através de uma série de escalas e graus de presença humana [@zylstra_connectedness_2014]. Na tentativa de superar essa divisão conceitual e perceptiva humano-natureza, e reconhecendo várias conceitualizações culturais não-ocidentais, sugerimos que "Natureza" seja, por definição, "Terra e vida (incluindo humanos)".

## **Povos Indígenas** {.unnumbered}

"Povos indígenas são grupos sociais e culturais distintos que compartilham laços ancestrais coletivos com as terras e os recursos naturais de onde vivem, ocupam ou de onde foram deslocados. A terra e os recursos naturais dos quais dependem estão intrinsecamente ligados às suas identidades, culturas, meios de subsistência, bem como ao seu bem-estar físico e espiritual. Muitas vezes, recorrem aos seus líderes e organizações tradicionais para obterem representação, que é distinta ou separada da sociedade ou cultura dominante. Muitos povos indígenas mantêm uma língua distinta da língua ou das línguas oficiais do país ou região em que residem" [@world_bank_indigenous_2023].

## **Pensamento sistêmico** {.unnumbered}

O pensamento sistêmico visa a conectar elementos uns aos outros dentro de alguma noção de uma entidade inteira. O pensamento sistêmico foca no pensamento de troncos usando modelos explícitos (suposições claras) em vez de modelos mentais implícitos (ou seja, suposições não reveladas e falta ou perda de pontos de dados). Esse ponto de vista ajuda a identificar e comunicar suposições subjacentes, bem como fornecer uma base para modelos a serem reproduzidos por outros. O pensamento sistêmico tem origens e aplicações em diversos campos e teorias. Em essência, requer uma abordagem transdisciplinar para conceitualizar, modelar e compreender fenômenos complexos a fim de induzir mudanças benéficas.

O pensamento sistêmico pode ainda ser definido como "uma abordagem holística para compreender as interações dinâmicas entre sistemas econômicos, ambientais e sociais complexos, e para avaliar consequências potenciais de intervenções" [@fiksel_triple_2013]. O pensamento sistêmico é, portanto, essencial para melhor prevenir as consequências negativas, não intencionais, das mudanças antrópicas nos sistemas da Terra.

## **Práxis** {.unnumbered}

Práxis conecta a separação entre teoria e prática. @freire_pedagogy_2018 descreve práxis como "reflexão e ação no mundo para transformá-lo". A práxis é fundamentalmente construída a partir da importância de se comprometer com a justiça social e a mudança de sistemas. Ela assegura a consideração de fatores sociais, políticos, econômicos e naturais, na pesquisa e suas aplicações.

## **Resiliência** {.unnumbered}

A Associação Americana de Psicologia [@american_psychology_association_resilience_2012] define resiliência como "o processo de adaptar-se bem em face à adversidade, trauma, tragédia, ameaças ou significantes fontes de estresse -- como em problemas relacionais e na família, sérios problemas de saúde ou estressores financeiros e no local de trabalho. Por mais que a resiliência envolva"recuar-se" destas experiências difíceis, também pode envolver um profundo crescimento pessoal. @southwick_resilience_2014 expande essa definição, entendendo que "determinantes de resiliência incluem uma série de fatores biológicos, psicológicos, sociais e culturais que interagem entre si e determinam como se responde a experiências estressantes".

## **Saúde Planetária** {.unnumbered}

Um campo rapidamente emergente focado na compreensão, comunicação e no direcionamento das extensivas ameaças à saúde humana associadas às rápidas condições de mudança ambiental. Essas incluem mudanças climáticas, perda da biodiversidade, mudanças no uso e na cobertura da terra, escassez de recursos, poluição global e alteração dos ciclos biogeoquímicos.

ou

Um campo emergente focado na compreensão das interligações dinâmicas entre as variações antrópicas nos sistemas naturais da Terra e a saúde humana em várias escalas, e a utilização dessas compreensões emergentes para encontrar soluções a fim de integrar o bem-estar de nossa biosfera

ou

"Saúde humana e Saúde Planetária são a mesma coisa... Prejudicar a Terra é prejudicar a si mesmo" [@prescott_canmore_2018].

## **Sistemas complexos** {.unnumbered}

Sistemas compostos por um grande número de componentes interativos, sem controle central, cujo comportamento "global" emergente -- descrito em termos de dinâmica, de processamento de informação e/ou adaptação -- é mais complexo do que se pode explicar ou prever a partir da compreensão da soma do comportamento dos componentes individuais. Sistemas complexos são geralmente capazes de se adaptar às mudanças de inserção/ambiente e, nestes casos, por vezes referidos como sistemas adaptativos complexos.

## **Transdisciplinaridade** {.unnumbered}

Conforme definido pela Escola de Saúde Pública de Harvard, "Pesquisa Transdisciplinar é definida como esforços de pesquisa conduzidos por pesquisadores de diferentes disciplinas trabalhando em conjunto para criar inovações conceituais, teóricas, metodológicas e translacionais que integram e vão além de abordagens disciplinares específicas, para resolver um problema comum".

Entretanto, a transdisciplinaridade também pode ser estendida para incluir um modo de ser. @rigolot_transdisciplinarity_2020 eplica que "quando a transdisciplinaridade é considerada um jeito de ser, é indissociável da vida pessoal e vai muito além das atividades profissionais de um pesquisador".

"A transdisciplinaridade reconhece que um modo acadêmico ou disciplinar de pesquisa está mal equipado para entender, e muito menos abordar, os complexos desafios que a sociedade atual enfrenta, dada a diversidade de perspectivas envolvidas \[na sociedade atual\]. Em vez disso, incentiva processos de aprendizagem compartilhados que envolvem a sociedade e permitem que os problemas sejam definidos, pesquisados e resolvidos independentemente de qualquer disciplina (científica) única. Outra característica importante da pesquisa transdisciplinar é que ela complementa os critérios científicos tradicionais de"objetividade" (por exemplo, as ciências naturais) com domínios subjetivos e normativos nos quais as visões de mundo, os valores e a ética da sociedade são expressos. Ao superar essas divisões, a relevância e a capacidade da ciência de abordar problemas socioecológicos são aprimoradas pela probabilidade de que a pesquisa (o "saber") seja efetivamente usada na implementação (o "fazer"). As abordagens transdisciplinares são, portanto, vitais para a ciência da sustentabilidade" [@zylstra_connectedness_2014].
