# Interconexão na Natureza

> *"Na visão de um futuro saudável, é importante criar as condições que permitam a superação da dissonância entre 'estar na natureza' (ou seja, a natureza que nos cerca) e 'ser da natureza' (ou seja, a natureza que nos incorpora)."*
>
> --- @redvers_molecular_2020

> *"A Primeira Lei da Ecologia é que tudo está conectado com tudo".*
>
> --- Bary Commoner

Compreender nosso papel na Natureza como espécie e como indivíduos é fundamental na ciência e prática da Saúde Planetária. Entretanto, a interconexão na Natureza tem sido um conceito marginalizado e ignorado historicamente. Por isso, entendemos que reimaginar nossa relação na Natureza é uma tarefa central e urgente das instituições de educação.

Para começar este modelo \[educacional\] devemos primeiro refletir sobre *por que* nossa civilização continua a superexplorar a Natureza em ritmo acelerado. Apesar das evidências cumulativas de nossa interdependência com a biosfera, as perspectivas e atitudes consequentes de nossa civilização não evoluíram adequadamente. Prosseguimos com a extração excessiva de recursos naturais, apesar do consenso científico de que esse comportamento é insustentável. Além disso, as instituições acadêmicas continuam a negligenciar a importância de compreender e melhorar nosso relacionamento com a Natureza. Essa atitude é, em parte, um sintoma de uma síndrome maior pela qual sofremos de uma incapacidade de reconhecer nossa interdependência com ecossistemas prósperos e saudáveis. Essa noção encontra ressonância em uma iniciativa recente intitulada @noauthor_os_2015, onde grandes estudiosos discutem visões de mundo que levariam a uma atitude mais harmoniosa e compassiva para com a Terra.

Existem várias explicações para nossa desconexão com a Natureza. A chegada compulsória de paradigmas eurocêntricos introduziu uma forma de conhecimento que incluía a dominação e a exploração da Natureza; o cartesianismo, uma visão dualística do mundo, levou ao reducionismo metodológico, um marco histórico da ciência ocidental. O cartesianismo propõe que os humanos podem ser observadores objetivos de partes redutíveis dos sistemas naturais. Esse paradigma reducionista, discutivelmente, levou a muitos avanços na saúde humana em certas esferas. No entanto, o holismo e as noções de interconexão têm sido frequentemente uma casualidade dessa abordagem. Além do cartesianismo, a rápida urbanização, a alienação sobre a origem dos alimentos, as mentalidades coloniais e de dominação, a compreensão do progresso como ganho de capital financeiro, a ideia de propriedade do "capital natural", o individualismo predominante, a visão da Natureza como um adversário, as dinâmicas tóxicas de gênero (ou seja, masculinidades tóxicas), e a sobrecarga sensorial e dessensibilização agravaram a nossa separação da Natureza [@zylstra_connectedness_2014].

Esses fatores mencionados explicam, pelo menos parcialmente, porque algumas sociedades se veem como independentes -- não dependentes -- da Natureza. Esta falsa separação entre humanos e Natureza perpetua uma cultura ilusória de dominação da Natureza, induzindo muitas das crises ambientais atuais. Quando humanos pensam e se comportam como se estivessem *separados* da Natureza, seja como observadores passivos ou como participantes ativos na dominação consciente ou inconsciente dos sistemas naturais, o resultado pode ser a ruptura dos limites planetários, com risco de vida. Estamos de fato experimentando muitos desses distúrbios hoje, incluindo a mudança climática, a sexta extinção em massa, o desmatamento, a acidificação dos oceanos e as doenças infecciosas emergentes, para citar alguns. Para sobreviver, os humanos devem mudar a mentalidade e a narrativa comum de separação, apatia e dominação para interconexão, empatia e parceria.

A Dimensão da Interconexão na Natureza (INN) é centrada em uma continuação de modelos similares descritos no campo da ecopsicologia, educação ambiental e ciências relacionadas à sustentabilidade, incluindo, por exemplo, "conexão humano-natureza", "conexão \[da/na/com a\] natureza" ou "relação com a natureza" [@zylstra_connectedness_2014]. Esta abordagem é simultaneamente informada por visões de mundo, sistemas de conhecimento e tradições de povos indígenas e outras culturas que ainda mantêm seu senso de interconexão dentro de toda a Natureza. Nesta dimensão, nos referimos à "interconexão" como um indicador de mutualismo, reciprocidade e simbiose. Usamos o termo "na" para denotar que os humanos são parte da Natureza e não separados dela. Finalmente, definimos a palavra "Natureza" encapsulando a Terra e a vida (incluindo humanos).

Acreditamos que unir formas de conhecimento, respeitosamente, com parceria direta e engajamento ético adequado facilitará o surgimento de co-benefícios para pessoas, comunidades e para nosso planeta. Isso inclui a consideração dos paradigmas de conhecimento indígenas *e* ocidentais, ao invés de sistemas de conhecimento indígenas *contra* ocidentais, na educação e na prática [@redvers_molecular_2020]. Assim, a dimensão da INN reconhece diversos conhecimentos e tradições espirituais, especialmente de povos indígenas (@tbl-1), que incorporam a profunda interconexão dos humanos na Natureza.

Ao perceber o vínculo entre humanos e Natureza, desejamos promover um novo éthos que dê suporte para sistemas socioecológicos vibrantes e resilientes. Uma abordagem de INN envolve o cognitivo (senso de conexão), o afetivo (componente de cuidado) e o comportamental (compromisso de agir). A INN vai além da simples transmissão de conhecimento via interações socioecológicas tradicionalmente oferecidas em instituições educacionais e espera superar tentativas superficiais de curto prazo de "reconectar" com ou "passar um tempo" na Natureza. Não é apenas o contato com a natureza, mas a natureza do contato o que mais importa.

A INN pede que aspectos cognitivos, afetivos, comportamentais e espirituais, se apropriados, sejam incorporados ao elaborar estratégias educacionais [@zylstra_connectedness_2014]. Embora ainda haja uma lacuna no entendimento sobre quais estratégias de educação funcionam mais efetivamente para "reconectar-se" com a Natureza, exemplos não faltam (ver, por exemplo, a Tabela 3 em @zylstra_connectedness_2014).

Reconhecemos haver ainda muitas maneiras de mudar nossa narrativa cultural em direção a uma compreensão mais abrangente da INN. Um instrumental nessa transição é o conceito de "Visão com Dois Olhos" do Mi'kmaq Élder Albert Marshall. Este termo descreve o benefício de respeitar e contar com múltiplas perspectivas [@bartlett_two-eyed_2012]. Em outras partes do mundo, é chamada abordagem de "Duas Vias" ou "Ambas as Vias". Por exemplo, o povo Yolŋu do nordeste da Terra de Arnhem, na Austrália, usa a palavra "Ganma" --- o lugar onde água doce e água salgada se encontram e se misturam --- para se referir à mistura de sistemas paralelos de conhecimentos ocidentais e indígenas [@verschuuren_mixing_2015 @weir_country_2012].

Nosso apreço pela INN é crucial para a educação em Saúde Planetária, pois estudos demonstram cada vez mais que passar tempo na Natureza torna os seres humanos mais saudáveis. De fato, estudos verificaram que estar na Natureza fortalece nosso sistema imunológico, reduz a depressão, melhora o humor, diminui o estresse, melhora a resiliência psicológica, o bem-estar mental e influencia positivamente na expectativa de vida [@kuo_how_2015]. Seja o resultado das estratégias da INN chamado "comportamento pró-ambiental", "comportamento pró-Natureza", "comportamento ambientalmente responsável", "comportamento de conservação", "comportamento ecológico" ou "comportamento sustentável" [@zylstra_connectedness_2014], a INN pode começar a construir formas de vida que afirmam e promovem o pleno florescimento dos sistemas naturais da Terra.

Esta dimensão da INN convida educadores a expandirem o conteúdo do ensino superior para incluir vozes e presença indígena, assim como outras tradições culturais, filosóficas, espirituais e científicas não dualistas, que centram a integração dos humanos na Natureza. Reconhecemos que a incorporação da INN nas instituições educacionais resolverá nossa desconexão da Natureza apenas de maneira parcial. Ao regenerar a relação humano-natureza, as instituições de ensino também precisam personificar a mudança que queremos ver nos alunos (por exemplo, desapegando-se de combustíveis fósseis). Hoje, não há um caminho único para alcançar e cultivar a INN. A consciência e a prática da INN serão, ao longo da vida, um processo único para cada indivíduo e cada contexto. Uma consciência profunda de pertencer à Natureza pode encorajar estudantes e profissionais a se comprometerem a proteger a Saúde Planetária. Como espécie humana, precisaremos que todos reconheçam a interconexão inata que existe na Natureza para promover as parcerias necessárias e criar um futuro saudável para todos.

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Um dos princípios transversais da Educação em Saúde Planetária afirma:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| "Uma compreensão do passado é necessária para resolver problemas do presente. Para entender a necessidade e urgência da Saúde Planetária, estudantes precisam estar conscientes das perspectivas históricas e dos marcos que estabeleceram a base para a fundação deste campo, incluindo aquelas perspectivas que têm sido historicamente marginalizadas ou ignoradas" [@martinez_native_2007].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Existem outras maneiras pelas quais podemos entender a relação entre humanos e Natureza. Essas maneiras de conhecer apontam para a interconexão na Natureza. Por exemplo, com os povos indígenas, os observadores e protetores originais dos ecossistemas, podemos aprender de forma respeitosa os comportamentos que afirmam e promovem o pleno florescimento dos sistemas naturais da Terra.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Por milênios, os povos indígenas de diversas localidades têm desenvolvido paradigmas baseados na experiência direta e na participação com a Natureza, enraizados na compreensão da interconexão. As experiências, observações e leis de existência dos povos indígenas em torno da noção de interconexão refletem-se em seus costumes, valores, sua dança, música, arte, medicina tradicional e suas expressões de espiritualidade, além de atuarem como zeladores de nosso mundo natural.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Como @harmin_stretching_2017 constataram, estar aberto às perspectivas indígenas permite que educadores, acadêmicos e estudantes obtenham compreensão e apreciação de sua interconexão e suas relações na Natureza.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| "Para os povos indígenas, há um reconhecimento de que muitas forças invisíveis estão em jogo nos elementos do universo e que muito pouco é naturalmente linear ou ocorre em uma grade bidimensional, ou em uma forma cúbica tridimensional. Povos indígenas estão familiarizados com as noções de conservação de energia, irregularidades em padrões e anomalias de forma e força. Através de longa observação, eles se tornaram especialistas em compreender a interconexão e o holismo de nosso lugar no universo" [@barnhardt_indigenous_2005].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Outras características importantes dos Sistemas de Conhecimento Tradicional Indígena (SCTI) incluem elementos de reciprocidade, relacionalidade, responsabilidade, holismo e a absoluta inseparabilidade do sagrado e secular. O aprendizado é baseado no terreno ou na localidade, experiencial, espiritual e intergeracional [@antoine_pulling_2018]. Um SCTI significativamente influente na América Latina, "Buen Vivir" ou "Sumak Kawsay" (em quíchua), é uma cosmovisão sagrada incluída parcialmente na constituição do Equador em 2008. Ela reconhece direitos intrínsecos da Natureza ou "PachaMama" e pode servir como inspiração para outros países também (por exemplo, a recente concessão de "personalidade jurídica" aos rios Whanganui na Nova Zelândia e Ganges na Índia).                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Como um exemplo da integração dos sistemas de conhecimento ocidental e indígena, podemos aplicar o conceito de "Visão com Dois Olhos" (ver descrição no texto) olhando através de um olho. Através dessa lente, podemos aprender a apreciar os achados de pesquisa que demonstram o fato de que não podemos confiar apenas na experiência visual da Natureza, mas, em vez disso, precisamos aprofundar nossas formas de interação na Natureza de modo a tornar os relacionamentos mais imersivos e significativos [@otto_nature-based_2017]. Podemos aprender como aprofundar nossa experiência centrada nos entes \[kins\] por meio da prática de interconexão, a qual pode permitir relacionamentos mais holísticos, locais, espirituais e intergeracionais. Nas palavras de Elder Albert Marshall, "Nenhum ser é maior do que o outro\... somos parte e parcela integrante do todo, somos iguais, e cada um de nós tem uma responsabilidade com o equilíbrio do sistema" [@bartlett_two-eyed_2012]. Talvez, esse diálogo entre culturas complementares possa ser informado pelo novo paradigma de Gaia, no qual a relação humano-ambiente tão intuitiva da sabedoria indígena é articulada na linguagem da ciência ocidental. |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Os termos "ecologia kincêntrica" e "kincentricidade" com o mundo natural são outros termos de particular importância para entender a INN e foram criados por estudiosos indígenas para traduzir conceitos de interconexão para a língua inglesa. Onde o antropocentrismo remete à exploração significativa e às indústrias extrativas, a "kincentricidade" é o relacionamento que sustenta a obrigação de renovar o planeta em harmonia com todos seus entes [@martinez_native_2007].                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Conhecimento Indígena e Interconexão Na Natureza (INN) {#tbl-1}

# **Principais conceitos e áreas de estudo Interconexão na Natureza** {.unnumbered}

Sistemas de conhecimento tradicionais

Conectividade na natureza (conexão humano-natureza)

Identidade ecológica

Diversidade epistemológica e humildade

Cosmovisões: do animismo ao cartesianismo

Visão com dois olhos

Centramento nos entes ("kincentricidade")

Resiliência

Pachamama (Mãe Terra), Gaia e outros conceitos semelhantes
