# Equidade e Justiça Social

> *"Podemos trabalhar juntos por um mundo melhor com homens e mulheres de boa vontade, que irradiam a bondade intrínseca da humanidade. Para fazer isso efetivamente, o mundo precisa de uma ética global com valores que deem sentido às experiências de vida e, mais do que instituições religiosas e dogmas, sustentem a dimensão imaterial da humanidade. Os valores universais da humanidade de amor, compaixão, solidariedade, cuidado e tolerância devem formar a base para esta ética global que deve permear a cultura, política, comércio, religião e filosofia."*
>
> *---* Wangari Maathai

Os impactos ambientais e na saúde de um planeta em mudança não são distribuídos de forma justa entre populações, espécies, regiões geográficas e gerações. Por exemplo, embora os países de renda alta e média-alta do mundo sejam responsáveis pela grande maioria das emissões de carbono, o fardo da mudança climática é desproporcionalmente sentido por populações vulneráveis, incluindo países de baixa renda, nações insulares, povos indígenas, jovens e gerações futuras.

A **Equidade** em Saúde Planetária incorpora direitos humanos e direitos da Natureza, dando a todas as populações humanas e ecossistemas -- presentes e futuros -- a oportunidade de atingir sua vitalidade plena [@prescott_canmore_2018; @noauthor_universal_2010]. Para tornar real um planeta mais equitativo, é necessário eliminar disparidades sistêmicas -- por exemplo, poder, riqueza, oportunidade ou estado de saúde, de modo que nenhuma população carregue cargas desproporcionais e evitáveis impactos ambientais e de saúde, enquanto outras conseguem prosperar. Equidade em Saúde Planetária também abrange um dos princípios descritos na Declaração de Canmore [@prescott_canmore_2018], "combater o elitismo, o domínio social e a marginalização". Para lidar com as iniquidades, deve-se dar atenção à saúde e ao bem-estar das populações e ecossistemas mais vulneráveis, à saúde precária e à degradação ambiental [@evison_new_2020]. Essas pessoas e espécies são contribuintes essenciais para soluções que abordam os desafios planetários que enfrentamos.

A promoção da equidade em Saúde planetária requer justiça distributiva -- visando novas maneiras de compartilhar fardos -- e justiça compensatória -- garantindo que aqueles lesados sejam compensados de forma justa por aqueles que os lesaram [@shanks_justice_2012]. Também requer justiça social e processual, destacando as desigualdades [@evison_new_2020], lutando pela mudança e garantindo que grupos vulneráveis tenham oportunidades de participar de forma significativa nas tomadas de decisão sobre as políticas que os afetam. Por fim, é imperativo considerar a justiça e equidade intergeracional, ambiental e das demais espécies, garantindo que as ações da geração presente protejam a saúde das gerações futuras.

Seguindo a compreensão da conexão entre as mudanças em nosso planeta conduzida pelos humanos e suas consequências [@evison_new_2020] para as populações descritas acima, soluções devem ser encontradas para enfrentar esses desafios [@foster_planetary_2020]. A Declaração de Canmore de 2018 [@prescott_canmore_2018], no Canadá, seguindo a Carta de Ottawa para Promoção da Saúde de 1986, [@world_health_organization_first_1986] oferece princípios norteadores para a ética em Saúde Planetária necessária para a concepção de potenciais soluções [@foster_planetary_2020; @potvin_twenty-five_2011; @prescott_canmore_2018].

Os processos de Educação em Saúde Planetária devem primeiro *reconhecer* as iniquidades estruturais e as raízes dos desafios da Saúde Planetária. Injustiças históricas e políticas, incluindo colonialismo, supremacia branca, **racismo**, patriarcado, capitalismo e neoliberalismo, contribuíram para a privação de direitos de populações, inclusive por meio da degradação de nosso meio ambiente que impede a vitalidade planetária. Ao trabalhar em prol da justiça, inclusão, diversidade e equidade, profissionais da Saúde Planetária devem se *comprometer* a imaginar alternativas ousadas e implementar práticas que abordem as causas profundas da injustiça dentro e entre as sociedades. Os grupos afetados, incluindo povos indígenas, continuam a demonstrar **resiliência** às mudanças ambientais e sociais em grande escala resultantes de processos colonizadores em andamento. Profissionais da saúde planetária podem aprender com as pessoas afetadas, priorizando sua riqueza de conhecimento para potenciais soluções (ver a Dimensão da Interconexão na Natureza).

A Educação em Saúde Planetária também deve ajudar estudantes a identificar *prioridades* para *ação* de modo a remodelar as instituições, por exemplo, leis, serviços de saúde, educação, que reproduzem as desigualdades ambientais e influenciam as condições de vida no planeta. Compreender os sistemas de poder pode viabilizar soluções que melhorem os resultados da Saúde Planetária. Embora intervenções voltadas para mudanças de comportamento no nível individual e familiar continuem ganhando destaque, esse enfoque individualista pode sobrecarregar as populações já afetadas pelas iniquidades. Na verdade, essa abordagem pode resultar em uma distração das responsabilidades estruturais, políticas e institucionais para promover Saúde Planetária. Por exemplo, não podemos atenuar as mudanças climáticas sem responsabilizar as 20 empresas responsáveis ​​por um terço das emissões mundiais de carbono. Além disso, não podemos promover a segurança alimentar sem responsabilizar as empresas transnacionais da indústria agroalimentar que governam e controlam o sistema alimentar mundial, conforme observado pelo Atlas Agroalimentar [@chemnitz_agrifood_2017]. Para transformar os sistemas de injustiça, no entanto, movimentos de poder em grande escala devem continuar a ganhar fôlego (ver a próxima seção).

Para promover equidade em Saúde Planetária, é essencial priorizar as necessidades das populações e ecossistemas mais afetados. Isso inclui apoiar resiliência, abordagens baseadas em pontos fortes, capacidade de antecipar e mitigar riscos, e uma transição justa. Para realizar isso, a prática profissional na Saúde Planetária requer humildade cultural, empatia e a promoção da participação inclusiva e diversa na definição de soluções. O alcance da justiça e equidade também exige o reconhecimento do próprio poder, influência, viés e recursos; além da responsabilidade de usar esses privilégios para trabalhar em prol de um planeta mais saudável, bem como priorizar a inserção dos menos privilegiados. **Finalmente, aprendizes devem conseguir aplicar os princípios de justiça social e equidade às questões de Saúde Planetária e às práticas profissionais.**

# **Principais conceitos e áreas de estudo sobre Equidade e Justiça Social** {.unnumbered}

Acessibilidade

Equidade e Iniquidade

Justiça social, distributiva, intergeracional e de múltiplas espécies

Os Direitos da Natureza

Humildade Cultural

Empatia

Privilégio

Racismo e Opressão
