# Avistando o Futuro {.unnumbered}

Neste momento crucial da história da humanidade, enfrentamos escolhas que impactam nossas próprias vidas e vidas de gerações vindouras. Cabe a nós influenciar a saúde humana e ambiental, tanto agora como no futuro, quer isso signifique melhorar o nosso bem-estar global ou pôr em risco a saúde do nosso planeta. Como espécie, fizemos enormes progressos em nossa trajetória para universalizar os direitos humanos mais básicos: por exemplo, o acesso à educação e às tecnologias que salvam vidas, redução da pobreza, aumento da expectativa de vida e progresso em direção à equidade de gênero. Contudo, os benefícios dos nossos avanços não têm sido distribuídos equitativamente, e agora, a contínua disrupção dos nossos sistemas naturais ameaça nossos passos adiante. Assim, não podemos mais simplesmente manter o *status quo* \[as coisas como estão\]. Os futuros profissionais de todas as disciplinas têm um papel vital a desempenhar na interrupção dos negócios habituais e na construção de um novo futuro equitativo e saudável. Entretanto, não podemos alcançar a mudança necessária sem uma mudança profunda no nosso sistema educacional.

Existem inúmeras oportunidades para melhorar nossas estratégias educacionais. Nunca na história fomos capazes de nos conectar, comunicar, criar redes e disseminar conhecimento como neste momento. Portanto, embora reconheçamos que a reforma educacional é um processo gradual, apelamos a uma mudança profunda nas abordagens educacionais, com a esperança de que a mudança ocorra de forma acelerada.

Instituições, educadores e aprendizes que decidirem incorporar este plano em seus esforços educacionais têm de se afastar de uma abordagem habitual, fragmentada da educação. De modo a incorporar a Saúde Planetária como uma matriz norteadora de implementação em escala institucional, os planos de ação das instituições devem considerar a contextualização, transdisciplinaridade (incluindo a **diversidade epistemológica**), o foco nas competências "essenciais" e nas abordagens educacionais transformadoras, orientadas para soluções, baseadas em ações [@aacu_essential_2021]. A liderança universitária, políticos, educadores e pesquisadores são cruciais no caminho para a mudança. Estudantes e jovens profissionais talvez sejam os mais essenciais na condução e sustentação do caminho para o futuro. Tal como referido neste documento, a mudança só ocorrerá de forma sustentável e equitativa com o envolvimento de todas as partes interessadas.

A adoção da Educação em Saúde Planetária deve se tornar um componente central para enfrentar os urgentes desafios ambientais e de saúde que enfrentamos. Esperamos que esta transformação na educação fomente comunidades locais e globais para trabalhar em prol do bem-estar, da justiça e de um planeta auspicioso para todos.
