# Construção de Movimento e Mudança de Sistemas

> *"Aqui, agora é onde traçamos a linha. O mundo está acordando. E a mudança está chegando, quer você goste ou não."*
>
> --- Greta Thunberg

> *"Nunca duvide que um pequeno grupo de cidadão pensantes, comprometidos, possa mudar mundo; na verdade, é a única coisa que sempre tem acontecido.*"
>
> --- Margaret Mead

Poderíamos concordar que a saúde do planeta precisa de restauração urgente, mas o *como* e *quem* desse processo permanecem questões incertas. Em nossa visão, mudança (ou seja, ação) requer relações inclusivas, estratégia bem pensada, comunicação eficaz e parcerias transformacionais. Daí o mantra de construção de movimento: "Vá devagar para se mover rápido". A dimensão da Construção de Movimento e Mudança de Sistemas refere-se às habilidades, conhecimentos, ferramentas, valores e atitudes necessárias que aprendizes precisarão para construir um movimento que apoie mudança de sistemas e a Grande Transição para um futuro justo e sustentável. Acreditamos que uma mudança na visão ou no propósito compartilhado pode mudar profundamente um sistema.

Tradicionalmente, a educação superior, especialmente nas artes liberais, inclui uma visão geral de muitas áreas diferentes do conhecimento para explorar grandes desafios ainda a serem resolvidos. Infelizmente, a educação não oferece frequentemente uma narrativa adicional para reunir essas disciplinas. Estudantes podem aprender sobre os impactos na saúde e as disrupções nos sistemas naturais da Terra causadas pelos humanos, mas podem não aprender sobre soluções eficazes. Mesmo quando exploram a ciência das soluções emergentes, podem não aprender como construir um movimento efetivo de mudança.

Como a *Dimensão da Construção de Movimento e Mudança de Sistemas* enfatiza, é necessário construir movimentos efetivos para resolver a crise urgente de Saúde Planetária. No entanto, ao contrário da crença popular, movimentos não surgem simplesmente em resposta a um determinado momento. Pode parecer, para alguns, que mudanças no comportamento social podem acontecer muito de repente, quando, na verdade, geralmente é preciso uma grande visão, construção de rede \[*network*\] e estratégias nos bastidores [@howard_targeted_2020]. Um pequeno número de indivíduos pode reunir ações para uma mudança notável. Reconhecemos que será preciso uma Grande Transição para restaurar a Saúde Planetária, mas também será necessário um movimento em grande escala para isso acontecer.

Conforme observado na *Dimensão Pensamento Sistêmico / Abordagens Baseadas na Complexidade em Saúde Planetária*, fronteiras disciplinares contrariam o objetivo de uma visão compartilhada de Saúde Planetária. Portanto, reconhecer e promover a transdisciplinaridade é o primeiro passo na adesão de uma nova visão para Saúde Planetária. Em 1994, no Primeiro Congresso Mundial de **Transdisciplinaridade**, o Centro Internacional para Pesquisa Transdisciplinar (CIRET) adotou a Carta da Transdisciplinaridade [@nicolescu_charter_1994]. A Carta declara:

*A transdisciplinaridade complementa abordagens disciplinares. Ocasiona o surgimento de novos dados e novas interações a partir do encontro entre as disciplinas. Nos oferece uma nova visão da Natureza e da realidade. A transdisciplinaridade não busca o domínio de várias disciplinas, mas visa abrir todas as disciplinas para o que compartilham e para o que está além delas"* (Artigo 3).

O segundo passo para criar uma visão compartilhada é desenvolver uma narrativa que foca na inclusão e na esperança. Uma visão que é capaz de conduzir um movimento efetivo deve conseguir incorporar diferentes formas de conhecimento, como estar fundamentada em uma narrativa que se estende por valores essenciais compartilhados. Marshall Ganz, o renomado intelectual da organização comunitária, cunhou o termo "Narrativa Pública" [@howard_targeted_2020] para descrever a estrutura para contação de histórias que "comunicam os valores que têm nos convocado à liderança, os valores que nos unem, e os desafios que devemos superar juntos" [@ganz_leading_2008].

Movimentos efetivos exigem relacionamentos saudáveis consigo mesmo e com os outros. Aprendizes precisam discernir onde podem contribuir de forma única para estimular a mudança dos sistemas; precisam desenvolver uma compreensão dos interesses, conhecimentos e habilidades exclusivos que podem oferecer; e devem ser empoderados para aprender autonomia para desenvolver e compartilhar suas contribuições pessoais.

Além de compreender o papel único que aprendizes podem desempenhar na realização de soluções em Saúde Planetária, eles também precisam aprender como desenvolver e manter \[suas\] redes \[*networks*\]. Redes conectam pessoas entre disciplinas, geografias e gerações. Redes são mais fortes quando são amplamente inclusivas. Redes são a única maneira de construir a capacidade necessária para \[solucionar\] as ameaças atuais à Saúde Planetária.

É essencial que essas relações sejam baseadas na parceria ao invés da dominação. Relações centradas na dominação são organizados de forma rígida -- a comunicação flui somente de cima para baixo e líderes usam vergonha, culpa e medo para manter o estado das coisas \[*status quo*\]. Nas relações baseadas na pareceria, há respeito mútuo e valorização de todas as contribuições, de modo que a comunicação flui de ambos os lados e líderes usam influência e encorajam toda a rede de colaboradores a alcançar seu potencial total. Diferenças no uso do poder são óbvias; líderes que orientam por meio da dominação usam a abordagem do "poder sobre", enquanto líderes que orientam por meio da parceria usam a abordagem do "poder com" [@sinnot_organizing_2014].

É importante notar que a construção de parcerias saudáveis é um processo. Para que as relações permaneçam efetivas, elas não podem ser negligenciadas. Elas devem ser nutridas e mantidas ao longo do tempo. De fato, conforme os psicólogos @sinnot_organizing_2014, "quando nutridas ao longo do tempo, as relações sustentam motivação e inspiração e se tornam uma fonte importante de aprendizagem e desenvolvimento contínuo para pessoas e comunidades que compõe suas campanhas organizacionais".

Uma estratégia efetiva pode unificar os membros de um movimento em sua visão e ações. Para atender aos objetivos desta dimensão, aprendizes devem ser capazes de inspirar pessoas através de uma narrativa (por exemplo, na forma de uma teoria da mudança) que as orienta em direção ao futuro que imaginam. Entretanto, mesmo quando a visão-inspiração está presente e a estratégia é efetiva, mudar sistemas complexos pode levar muito tempo. É, portanto, essencial que ativistas individuais e redes de movimento continuem a construir capacidade, permitindo que os integrantes se aproximem e se afastem conforme necessário para manter a resiliência ao longo do tempo. Além de alinhar uma visão, a contação de histórias pode nos lembrar de desafios históricos que foram superados pelo trabalho em conjunto, o que nos dá esperança de que as gerações futuras um dia contarão a história de nosso movimento bem-sucedido para restaurar a saúde do planeta.

**Enfim, esperamos que estudantes possam alinhar visões para um futuro justo e sustentável, assim como inspirar parcerias intersetoriais e inclusivas para co-criar um futuro melhor para todos os integrantes da Saúde Planetária.**

# **Principais conceitos e áreas de estudo sobre Construção de Movimento e Mudança de Sistemas** {.unnumbered}

Urgência e esperança

Visão estratégica

Teoria da Mudança

O Espectro de Aliados

Advocacia

Empreendedorismo

Inovação

Empoderamento, autonomia e agenciamento

Colaboração -- participação

Inclusão/diversidade

Capacitação

Resiliência
