# Notas de Tradução {.unnumbered}

O Modelo para Educação em Saúde Planetária é um passo importante para a implementação e disseminação de conhecimentos produzidos pelo campo da Saúde Planetária mundo afora e, consequentemente, para a Grande Transição proposta por este campo: uma mudança abrangente na maneira como os seres humanos interagem entre si e com os sistemas naturais da Terra. No entanto, a acessibilidade e a compreensão do modelo original, construído e publicado na língua inglesa, podem ser limitadas àquelas pessoas familiarizadas com essa língua. Traduções tornam-se, portanto, cruciais.

Tais traduções podem servir como catalisadores de implementação e disseminação do modelo educacional em línguas diversas. Nosso objetivo foi dar início a esse processo de catalização. A versão brasileira do Modelo para Educação em Saúde Planetária, aqui apresentada, contou com um processo de tradução composto por três fases: (1) uma tradução livre; (2) uma revisão linguístico-discursiva; e (3) uma revisão técnica.

A primeira fase do processo de tradução foi iniciada para ser utilizada como referencial teórico para estudantes de um curso de introdução à saúde planetária não familiarizados com a língua inglesa, assim impedidos de usufruir do modelo educacional original. O curso tratava-se de uma disciplina optativa oferecida no Programa de Mestrado em Saúde e Educação da Universidade de Ribeirão Preto, São Paulo, Brasil. As cinco dimensões do modelo educacional foram traduzidas pelo professor responsável pela disciplina e partilhadas com os alunos ao longo do semestre. Os demais componentes do modelo foram traduzidos posteriormente.

A segunda fase tratou de analisar as escolhas linguístico-discursivas realizadas na primeira fase e possíveis deslocamentos de sentidos. O referencial teórico para essa análise foi o campo de conhecimentos da Análise de Discurso materialista. Na terceira fase desse processo de tradução, a chamada revisão técnica, tratou de verificar se os conceitos e termos referentes ao campo de conhecimentos da Saúde Planetária permaneciam adequados.

Esperamos que essa versão brasileira do Modelo para Educação em Saúde Planetária facilite a implementação e disseminação desse modelo nos sistemas educacionais brasileiros, assim como em outros sistemas educacionais de língua portuguesa. Esperamos também que o processo de tradução em três fases aqui apresentado possa ser considerado como um possível referencial para futuros esforços de tradução do Modelo para Educação em Saúde Planetária para outras línguas.

**Saulo Barboza, Jacob dos Santos Biziak e Giselle Medeiros Mesiara**

Saulo Barboza é Professor Titular do Programa de Mestrado Profissional em Saúde e Educação da Universidade de Ribeirão Preto; coordenador do Grupo de Estudos Planetários; e pesquisador colaborador do Grupo de Estudos do Discurso, junto ao Instituto Federal de São Paulo, campus Sertãozinho.

Jacob dos Santos Biziak é docente do curso de Letras do Instituto Federal de São Paulo, campus Sertãozinho; docente, pesquisador e orientador do Programa de Pós-Graduação em Estudos Literários da Universidade Estadual Paulista, campus Araraquara.

Giselle Medeiros Mesiara é consultora internacional de promoção de saúde global e sustentabilidade, certificada pela *University College Copenhagen*, Dinamarca. Atua como pesquisadora, educadora e coordenadora em projetos europeus e brasileiros de ações sustentáveis para a saúde planetária.
